name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      env:
        OPENSHOCK_TOKEN: ${{ env.OPENSHOCK_TOKEN }}
        SHOCKER_TEST_ID: ${{ env.SHOCKER_TEST_ID }}
        USER_TEST_ID: ${{ env.USER_TEST_ID }}
